import { Box, Heading } from "@chakra-ui/react"
const LastFooter = () => {
    return (

        <Box width=" 90%" ml="90px" mr="90px" mt={0}   bg="#f7f7f7" fontSize={'12px'} color="#777777" >
            <Box   > <Heading as='h6' size='xs'  >Men:</Heading>      <p       >Shirts for Men / Casual Shirts for Men / Formal Shirts for Men / Hoodies for Men / Cotton Shirts for Men / T Shirts for Men / Polo T shirts / Kurta Pajama for Men / White Shirt / Black Shirt / Lower for Men / Trousers for Men / Jacket for Men / Formal Pants for Men / Tracksuit for Men / Jeans for Men / Kurta Payjama Sets / Kurta for Men / Blazer for Men / Sweater for Men</p>  </Box>

            <Box ><Heading as='h6' size='xs' lineHeight={'10px'} >Women:</Heading>  Tops for Women / Kurti / Cotton Sarees / Georgette Sarees / Chiffon Sarees / Net Sarees / Dresses for Women / Jumpsuit for Women / Jeans for Women / Salwar Suit / Bra / Jacket for Women / Night Dress for Women / Sweatshirt for Women / Shorts for Women / Readymade Blouse / Dupatta / T Shirt for Women / Shirts for Women / Skirts for Women / Ethnic wear for Women / Western Dresses for Women / Leggings for Women</Box>
            <Box  ><Heading as='h6' size='xs' lineHeight={'10px'}>Footwear:</Heading>  Men's Footwear / Casual Shoes for Men / Formal Shoes for Men / Loafers for Men / Slippers for Men / Boots for Men / Sandals for Men / Footwear for Women / Heels for Women / Sandals for Women / Shoes for Women / Sandals for Women / Slippers for Women / Boots for Women / Jutti for Women / Sports Shoes for Women</Box>
            <Box  ><Heading as='h6' size='xs' lineHeight={'18px'}>Home & Kitchen:</Heading> Wall Painting / Wall Stickers / Dream Catcher / Rangoli Designs / Clock / Wall Clock / Alarm Clock / Diya / Bean Bag / Laptop Table / Study Table / Wall Hanging / Ceiling Lights / Table Lamp / Hanging Lights / LED Bulbs / Torch Light / LED Lights / Flower Vase / Keychain / Rudraksha / Screwdriver</Box>
            <Box  ><Heading as='h6' size='xs' >Watch:</Heading >Watch For Men / Womens Watches / Smart Watch / Boys Watch / Girls Watch </Box>
            <Box  > <Heading as='h6' size='xs' lineHeight={'10px'}>Home Furnishing:</Heading> Bed Sheet / Mosquito Net / Mattress / Curtains / Sofa Cover / Blanket / Pillow / Carpet / Apron / Quilt / Floor Mat / Towel / Pillow Cover</Box>
            <Box  ><Heading as='h6' size='xs' lineHeight={'10px'}>Electronics:</Heading> Bluetooth Speakers / Headphones / Earphone / Ceiling Fan / Geysers / Trimmer / Hair Straightner / Hair Dryer / Water Purifier / Mixer Grinder / Gas Stove / Electric Kettle / Computer Mouse / Computer Keyboard / USB & HDMI Cables / Computer Antivirus</Box>
            <Box     > <Heading as='h6' size='xs' lineHeight={'10px'}>Mobiles Accessories:</Heading>Mobile Covers / Leather Mobile Covers / Printed Back Covers / Tempered Glass</Box>
            <br />
            Snapdeal is India's leading pure-play value Ecommerce platform. Founded in 2010 by Kunal Bahl and Rohit Bansal, Snapdeal is one of the top four online lifestyle shopping destinations of India. Snapdeal brings together a wide assortment of good quality and value- priced merchandise on its platform. Snapdeal's vision is to enable the shoppers of Bharat to experience the joy of living their aspirations through reliable, value-for-money shopping. With a personalized, multilingual interface and cutting edge technology, Snapdeal has simplified the shopping experience for its value-conscious buyers by showcasing the most relevant products- products that are a good functional fit with their needs and of a quality that lasts- thereby delivering true value to its customers. With its commitment to high service standards, Snapdeal suppliers operate under a well structured ecosystem that enables them to offer great quality products at affordable prices. With majority of the value-seeking, middle-income, price-conscious buyers coming from the non-metros, Snapdeal’s logistics networks powered by third party logistics cover more than 96% of India’s pin codes enabling order deliveries to more than 2500 towns and cities and expanding. Further, Snapdeal's mission is to become India’s value lifestyle omni-channel leader. We are excited about continuing to build a complete ecosystem around value commerce, where we can serve Bharat consumers wherever they are on their offline to online shopping journey. Snapdeal is part of the AceVector Group and one of India’s best-known e-commerce companies with an exclusive focus on the value segment.
            <hr />
            <br />
            <Box display={'flex'} justifyContent='space-between'  ><h2>Copyright © 2021, Snapdeal Limited. All Rights Reserved</h2><h3>Made for Bharat <i className="fas fa-heart"></i></h3></Box>
        </Box>
    )

}

export default LastFooter